# origin : https://github.com/googlesamples/android-custom-lint-rules/blob/main/.github/workflows/basic.yml

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      # AGP 8.2 requires 34.0.0-rc3 - see https://issuetracker.google.com/issues/236167971#comment36
      # and https://github.com/actions/runner-images/issues/7506#issuecomment-1533097084
      # TODO: Remove when AGP updates Build Tools to 34.0.0 and pre-installed in the runner
      #- name: Install Android Build Tools 34.0.0-rc3
      #  run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0-rc3"
      #  shell: bash
      - name: Build with Gradle
        run: ./gradlew :lint:build :lint:test